### ISSUE TITLE
SSL config issue after upgrade

### ISSUE THREAD

**Issue by conxuro** [Clommunity/cDistro#10]
From GoGS: Open conxuro opened this issue 7 months ago

If you have installed the HTTPS support (SSL), after upgrading the web interface (cloudy package: cdistro), when you go to the menu "System>SSL manager" it shows the message "HTTPS is not installed", even the HTTPS access is still available and connected.

It seems that the upgrade overwrites the /etc/cdistro.conf

**Comment by conxuro** [comment]
It may be related to issue #24

**Comment by rogerpueyo** [comment]
Not happening anymore.
