### ISSUE TITLE
Kimchi menu not moved (nor removed) to new ones

### ISSUE THREAD

**Issue by conxuro** [Clommunity/cDistro#26]
Kimchi service config menu is maintained in the "Community" menu and is not moved to the new "Community cloud".

If this service is not included in the newer versions, it should be removed completely from Cloudy's who had it already installed, or at least moved accordingly to the new menus.

Related to #24

**Comment by rogerpueyo** [comment]
> Kimchi service config menu is maintained in the "Community" menu and is not moved to the new "Community cloud".

To the best of my knowledge, it is not in the "Community" menu anymore, but in the "Personal cloud" menu (web/plug/menus/kimchi.menu.php): 
```
<?php
//menu/kimchi.menu.php
if (has_virtualization_extensions()) { addMenu(t('Kimchi'),'kimchi',t('menus_cloud_personal')); }
```

> If this service is not included in the newer versions, it should be removed completely from Cloudy's who had it already installed, or at least moved accordingly to the new menus.

The service is to be included once it is thoroughly tested and the interface is translated, so I believe it should not be removed at all.

>Related to #24

That makes sense.

**Comment by rogerpueyo** [comment]
Fixing #24 is needed
