### ISSUE TITLE
Too old Docker version

### ISSUE THREAD

**Issue by felixfreitag** [Clommunity/cDistro#38]
A Docker installed in Cloudy is v1.6.2.

Installing a recent Docker version 1.12.1, build 23cf638

It seems the Docker version that Cloudy installs does not exist anymore, Docker does not install on a Cloudy.

**Comment by rogerpueyo** [comment]
Debian currently ships, in the stable version, docker v1.6.2. https://packages.debian.org/search?keywords=docker.io

To install the newer 1.12.1 version, an external repository (Docker's one) must be added to Debian's sources.list file (see https://docs.docker.com/engine/installation/linux/debian/).

Is there a real need to install v1.12.1 (i.e. a feature not present in v1.6.2)?

**Comment by rogerpueyo** [comment]
Cloudy now installs the latest docker-ce (Community Edition). Closing.
