### ISSUE TITLE
HTTPS Manager when activated redirects http to https but the https fails to work 

### ISSUE THREAD

**Issue by leandro-navarro** [Clommunity/cDistro#56]
HTTPS Manager -> Install SSL 
cDistro/web/plug/controllers/ssl.php or the ssl.sh fails to configure the web server correctly. The redirection http -> https works but then the https session returns text results (like http) so the browser fails. Probably check how the script reconfigures the web server. Enabling this function makes the web interface UNUSABLE (Don't try at home alone!)
On the shell, the script to remove works although it throws a few errors.

**Comment by rogerpueyo** [comment]
I've tested it on several Cloudy instances and it seems to work properly. The "only" problem is that, when enabling HTTPS. the HTTP interface redirects the browser to the HTTPS one while the TLS certificate and the web server is being generated in the background and, in most machines, this takes a few seconds, so the HTTPS page needs to be reloaded. The user is now warned (https://github.com/Clommunity/cDistro/commit/0d4ed44a4e97c5c65e7b4a8e62083df64602b508#diff-9ec1b09fa8e91b2427acc600e4eeed96R14) about this fact, and suggested to reload the page after a few seconds.

It has been suggested in another issue to not redirect from HTTP to HTTPS, but to show a header warning the user about the fact that HTTPS is enabled and suggest them to use it.
