### ISSUE TITLE
[serf] Node names are not unique enough

### ISSUE THREAD

**Issue by rogerpueyo** [Clommunity/cDistro#64]
Two Cloudy instances with the same hostname make their respective Serf daemons join the Serf network with the same name. This is sad, because Names must be unique, so the one who joined later is kicked out.

``
root@debian:~# /opt/serf/serf agent -node=cc0c0cdc9bbe351f7cbfa7aaaf2eb5d7-5000 -bind=192.168.40.204:5000 -rpc-addr=127.0.0.1:7373 -profile=wan -join 192.168.40.57:5000
==> Starting Serf agent...
==> Starting Serf agent RPC...
==> Serf agent running!
         Node name: 'cc0c0cdc9bbe351f7cbfa7aaaf2eb5d7-5000'
         Bind addr: '192.168.40.204:5000'
          RPC addr: '127.0.0.1:7373'
         Encrypted: false
          Snapshot: false
           Profile: wan
==> Joining cluster...(replay: false)
    Join completed. Synced with 1 initial agents

==> Log data will now stream in as it occurs:

    2018/01/04 20:39:35 [INFO] agent: Serf agent starting
    2018/01/04 20:39:35 [INFO] serf: EventMemberJoin: cc0c0cdc9bbe351f7cbfa7aaaf2eb5d7-5000 192.168.40.204
    2018/01/04 20:39:35 [INFO] agent: joining: [192.168.40.122:5000] replay: false
    2018/01/04 20:39:35 [INFO] serf: EventMemberJoin: 91e145ef276fc34641726e7dc1235f6f-5000 192.168.40.57
    2018/01/04 20:39:35 [INFO] serf: EventMemberJoin: ecda079916ef89cc9a38ff7cc7fbfaf8-5000 192.168.40.96
    2018/01/04 20:39:35 [INFO] serf: EventMemberJoin: 37e28fcef61a16330cd382d2368d82de-5000 192.168.198.66
    2018/01/04 20:39:35 [INFO] serf: EventMemberJoin: ee1454a4fb14c99e4f108c9cc566a52c-5000 192.168.40.65
    2018/01/04 20:39:35 [INFO] serf: EventMemberJoin: bb02a3aa705a0abba7c61d7e278a577c-5000 192.168.40.122
    2018/01/04 20:39:35 [INFO] serf: EventMemberJoin: 290cea4a74c1d13d247d9dfbb022b672-5000 192.168.40.99
    ****2018/01/04 20:39:35 [ERR] memberlist: Conflicting address for cc0c0cdc9bbe351f7cbfa7aaaf2eb5d7-5000. Mine: 192.168.40.204:5000 Theirs: 192.168.40.80:5000****
    ****2018/01/04 20:39:35 [ERR] serf: Node name conflicts with another node at 192.168.40.80:5000. Names must be unique! (Resolution enabled: true)****
    2018/01/04 20:39:35 [INFO] serf: EventMemberJoin: d9b6b3fde057308500ccd8878667f4d7-5000 10.140.111.227
    2018/01/04 20:39:35 [INFO] serf: EventMemberJoin: 12547943063eb8b06aa26c70900a5cf7-5000 192.168.40.67
    2018/01/04 20:39:35 [INFO] serf: EventMemberJoin: a626f7754d12e659eb04a0cf3e23d201-5000 192.168.40.62
    2018/01/04 20:39:35 [INFO] serf: EventMemberJoin: 9029ce8641b11eb052d5b13997e9d53f-5000 192.168.40.91
    2018/01/04 20:39:35 [INFO] serf: EventMemberJoin: 82e6e022736d5b68de0aea7830da697a-5000 192.168.40.185
    2018/01/04 20:39:35 [INFO] serf: EventMemberJoin: 7d9f4711f650a2a08ccd53cd5403c149-5000 192.168.40.117
    2018/01/04 20:39:35 [INFO] serf: EventMemberJoin: 862948f4ec06c9e190e0ec20a693f494-5000 192.168.40.56
    2018/01/04 20:39:35 [INFO] serf: EventMemberJoin: 95cc2c0f9a9d2904c4c3a6fbaa4d7cdb-5000 192.168.40.183
    2018/01/04 20:39:35 [INFO] serf: EventMemberJoin: 2e46a2753cce1af21272d8971e2d2f6a-5000 192.168.40.135
    2018/01/04 20:39:35 [INFO] serf: EventMemberJoin: dacbc9836356570892a4b655077fe43d-5000 192.168.40.88
    2018/01/04 20:39:35 [INFO] serf: EventMemberJoin: 20c6ae2b067427648c225c38c28cbfdc-5000 192.168.40.73
    2018/01/04 20:39:35 [INFO] serf: EventMemberJoin: aad71d25893627f951b4fd1de5d42a40-5000 192.168.40.76
    2018/01/04 20:39:35 [INFO] serf: EventMemberJoin: a108150ae16297a84837e6a42ff59799-5000 192.168.40.100
    2018/01/04 20:39:35 [INFO] serf: EventMemberJoin: f3a28293e4cb2411a4e4043dcca5c3c9-5000 192.168.40.199
    2018/01/04 20:39:35 [INFO] serf: EventMemberJoin: 69981851a97875768225f8eb358d3fcc-5000 192.168.10.51
    2018/01/04 20:39:35 [INFO] serf: EventMemberJoin: 84fea51e17c42d4992608850b4c4e5f4-5000 192.168.23.46
    2018/01/04 20:39:35 [INFO] agent: joined: 1 nodes
    2018/01/04 20:39:36 [INFO] agent: Received event: member-join
    2018/01/04 20:39:51 [WARN] serf: minority in name conflict resolution, quiting [0 / 32]
    2018/01/04 20:39:51 [WARN] serf: Shutdown without a Leave
    2018/01/04 20:39:51 [WARN] agent: Serf shutdown detected, quitting
    2018/01/04 20:39:51 [INFO] agent: requesting serf shutdown
    2018/01/04 20:39:51 [INFO] agent: shutdown complete

``

**Comment by felixfreitag** [comment]
Hola Roger,

> Two Cloudy instances with the same hostname make their respective  
> Serf daemons join the Serf network with the same name. This is sad,  
> because Names must be unique, so the one who joined later is kicked  
> out.

-> Cloudy node:
http://10.139.40.117:7000

te un nom unic: cloudyDeb9CL2a40117
que generaria un serf node name unic.

Pero sigueix sense trobar serveis (al menys el que troba no arriba a la GUI):

No services.


mentre en CL:  serf members si que els troba ....

felix@cloudyDeb9CL2a40117:/opt/serf$ ./serf members
92e491001114e4c1bdee8a380a95d57e-5000  10.1.9.68:5000       alive    
services=QlpoOTFBWSZTWYT+544AAF/fgAAQEIVrcAcBXQqvp98qMADayDJJqYynmlNNPUAAD1GnqDIVPE9UyGgaNDTR6IDQJVPSTANAJkYE0w1GFiy/CCL4ZZzmZADBRsaDoxYjwUCIIINcilGkM97JOWNoViraq3CIRCqMnIAoDUYnedxmZFthTbaXD/jEwQ84BIRKlCwJYlJz6zx7xwl5D+8d/KXhYG+fw8QugUqoVMjJQyiQvGrJwXoFFh9BgjIaiAOUL9VS8yOEAkKLcgdCln0Fwvk+KBoamLx2Fga0pM5AzOCnWKVR4d/F3JFOFCQhP7njgA==
d9b6b3fde057308500ccd8878667f4d7-5000  10.140.111.227:5000  alive    
services=QlpoOTFBWSZTWWCGnesAAGLfgAAQEIV/kAcBXQqvp98qMADayDJJqYynmlNNPUAAD1A9QZT1KeCjQAG1B6jamgNAlU9IAAIwATCHpNMskMcn4tD1r4NR8Fij4bjguMR0KBEEEGP4pRnDKbJOWNoViraq3CIRCqMnIAoDUYg6zUqbNxxFa0YiKMyBxLmnk8Me4tBKJZWtK33P7w8iXu/bOHhONLvhtCyjIkEzAwQahAUGfCQMoiMz6DQxqGogD9hfoqXmRwgEhRbkDoUs9guF8nxQNDUxeO4sDWlJn4DM4KdIpVHh38XckU4UJBghp3rA
82e6e022736d5b68de0aea7830da697a-5000  10.139.40.185:5000   alive    
services=QlpoOTFBWSZTWaMUGNQAAEdfgAAQEIdvcAMBXQqvp98qMAC21DUNTFPJDTNDRBo02jQAim1BoNqaaAAGgNACVNFD009UyaPUA9TTEB6hkrTjAvNK3gYPGm2zDgoDGa9EVDyiOAUOgQkTxEcEAYzKkbGsYgzLkZEQtJFg6RoGx5irIM486Di1qK1BLUOoSYxGNCEMsFZr1xfGNyR/g4HlahCHjcES14HbHqFNFEibkcgofVftxIFZTrVCdT0IaWzPgQhw3tJIdkUE4HrGwFU9Y/cbNZyLuSKcKEhRigxqAA==
88904957ee6738511ed30c6b609aa8e0-5000  10.1.24.140:5000     alive



No pot haver un "fallo" en el codi que passi els dades a la GUI?


Felix

------------------------------------------------------------------------

root@cloudyDeb9CL2a40177:/opt/serf# ./serf agent  
-join=10.139.40.122:5000   -rpc-addr=127.0.0.1:7373  -bind=0.0.0.0:5000
==> Starting Serf agent...
==> Starting Serf agent RPC...
==> Serf agent running!
          Node name: 'cloudyDeb9CL2a40177'
          Bind addr: '0.0.0.0:5000'
           RPC addr: '127.0.0.1:7373'
          Encrypted: false
           Snapshot: false
            Profile: lan
==> Joining cluster...(replay: false)
     Join completed. Synced with 1 initial agents

==> Log data will now stream in as it occurs:

     2018/01/08 13:53:32 [INFO] agent: Serf agent starting
     2018/01/08 13:53:32 [INFO] serf: EventMemberJoin:  
cloudyDeb9CL2a40177 127.0.0.1
     2018/01/08 13:53:32 [INFO] agent: joining: [10.139.40.122:5000]  
replay: false
     2018/01/08 13:53:32 [INFO] serf: EventMemberJoin:  
91e145ef276fc34641726e7dc1235f6f-5000 10.139.40.57
     2018/01/08 13:53:32 [INFO] serf: EventMemberJoin:  
5c289d646e554cb985fb9f71874b7e0b-5000 10.228.207.24
     2018/01/08 13:53:32 [INFO] serf: EventMemberJoin:  
20c6ae2b067427648c225c38c28cbfdc-5000 10.139.40.73
     2018/01/08 13:53:32 [INFO] serf: EventMemberJoin:  
049b87059a92b464c7318ec181841122-5000 10.138.33.130
     2018/01/08 13:53:32 [INFO] serf: EventMemberJoin:  
e21d54f7c23a1b0688892ca58bcd9b5f-5000 10.1.24.158
     2018/01/08 13:53:32 [INFO] serf: EventMemberJoin:  
6eeaeae20c0cbe4457a777e7959b0be5-5000 10.1.192.34
     2018/01/08 13:53:32 [INFO] serf: EventMemberJoin:  
c6e794f06aa08ec25b47ce2a276660ed-5000 10.1.33.36
     2018/01/08 13:53:32 [INFO] serf: EventMemberJoin:  
88904957ee6738511ed30c6b609aa8e0-5000 10.1.24.140
     2018/01/08 13:53:32 [INFO] serf: EventMemberJoin:  
32f6ddf74c27101057cfeaebdec9298d-5000 10.138.0.2
     2018/01/08 13:53:32 [INFO] serf: EventMemberJoin:  
84fea51e17c42d4992608850b4c4e5f4-5000 10.138.23.46
     2018/01/08 13:53:32 [INFO] serf: EventMemberJoin:  
ee1454a4fb14c99e4f108c9cc566a52c-5000 10.139.40.65
     2018/01/08 13:53:32 [INFO] serf: EventMemberJoin:  
ecda079916ef89cc9a38ff7cc7fbfaf8-5000 10.139.40.96
     2018/01/08 13:53:32 [INFO] serf: EventMemberJoin:  
37e28fcef61a16330cd382d2368d82de-5000 10.139.198.66
     2018/01/08 13:53:32 [INFO] serf: EventMemberJoin:  
2af91bad3fbf1524dbc8bf5c9f19f82c-5000 10.228.207.15
     2018/01/08 13:53:32 [INFO] serf: EventMemberJoin:  
d9b6b3fde057308500ccd8878667f4d7-5000 10.140.111.227
     2018/01/08 13:53:32 [INFO] serf: EventMemberJoin:  
aad71d25893627f951b4fd1de5d42a40-5000 10.139.40.76
     2018/01/08 13:53:32 [INFO] serf: EventMemberJoin:  
a626f7754d12e659eb04a0cf3e23d201-5000 10.139.40.62
     2018/01/08 13:53:32 [INFO] serf: EventMemberJoin:  
dacbc9836356570892a4b655077fe43d-5000 10.139.40.88
     2018/01/08 13:53:32 [INFO] serf: EventMemberJoin:  
12547943063eb8b06aa26c70900a5cf7-5000 10.139.40.67
     2018/01/08 13:53:32 [INFO] serf: EventMemberJoin:  
9029ce8641b11eb052d5b13997e9d53f-5000 10.139.40.91
     2018/01/08 13:53:32 [INFO] serf: EventMemberJoin:  
2e46a2753cce1af21272d8971e2d2f6a-5000 10.139.40.135
     2018/01/08 13:53:32 [INFO] serf: EventMemberJoin:  
4c4c3a6fbaa4d7cdb93e4c99ac36193a-5000 10.139.40.184
     2018/01/08 13:53:32 [INFO] serf: EventMemberJoin:  
95cc2c0f9a9d2904c4c3a6fbaa4d7cdb-5000 10.139.40.183
     2018/01/08 13:53:32 [INFO] serf: EventMemberJoin:  
f3a28293e4cb2411a4e4043dcca5c3c9-5000 10.139.40.199
     2018/01/08 13:53:32 [INFO] serf: EventMemberJoin:  
bb02a3aa705a0abba7c61d7e278a577c-5000 10.139.40.122
     2018/01/08 13:53:32 [INFO] serf: EventMemberJoin:  
92e491001114e4c1bdee8a380a95d57e-5000 10.1.9.68
     2018/01/08 13:53:32 [INFO] serf: EventMemberJoin:  
7a27a2cdff59dd511d9b831db55af780-5000 10.1.24.157
     2018/01/08 13:53:32 [INFO] serf: EventMemberJoin:  
06e551893238d279178c794b27bedbca-5000 192.168.32.3
     2018/01/08 13:53:32 [INFO] serf: EventMemberJoin:  
a108150ae16297a84837e6a42ff59799-5000 10.139.40.100
     2018/01/08 13:53:32 [INFO] serf: EventMemberJoin:  
290cea4a74c1d13d247d9dfbb022b672-5000 10.139.40.99
     2018/01/08 13:53:32 [INFO] serf: EventMemberJoin:  
3ba7d8196069bb4d07d0ec22f605ccc0-5000 10.1.24.144
     2018/01/08 13:53:32 [INFO] serf: EventMemberJoin:  
cc0c0cdc9bbe351f7cbfa7aaaf2eb5d7-5000 10.139.40.204
     2018/01/08 13:53:32 [INFO] serf: EventMemberJoin:  
f9f304204240e67fcf140e7255e34449-5000 10.1.40.13
     2018/01/08 13:53:32 [INFO] agent: joined: 1 nodes
     2018/01/08 13:53:33 [INFO] serf: EventMemberJoin:  
82e6e022736d5b68de0aea7830da697a-5000 10.139.40.185
     2018/01/08 13:53:34 [INFO] agent: Received event: member-join
     2018/01/08 13:53:34 [WARN] memberlist: Refuting a suspect message  
(from: 84fea51e17c42d4992608850b4c4e5f4-5000)
     2018/01/08 13:53:34 [INFO] serf: EventMemberJoin:  
08569e435b959c031153a8eb7e2fd92c-5000 10.139.17.3
     2018/01/08 13:53:35 [INFO] agent: Received event: member-join
     2018/01/08 13:53:40 [INFO] memberlist: Suspect  
06e551893238d279178c794b27bedbca-5000 has failed, no acks received
     2018/01/08 13:53:42 [WARN] memberlist: Refuting a suspect message  
(from: 5c289d646e554cb985fb9f71874b7e0b-5000)
     2018/01/08 13:53:43 [INFO] serf: EventMemberJoin:  
91a4cc710cd678939bc57030033e63e4-5000 192.168.1.3
     2018/01/08 13:53:44 [INFO] agent: Received event: member-join
     2018/01/08 13:53:45 [WARN] memberlist: Refuting a suspect message  
(from: 91e145ef276fc34641726e7dc1235f6f-5000)
     2018/01/08 13:53:47 [WARN] memberlist: Refuting a suspect message  
(from: 12547943063eb8b06aa26c70900a5cf7-5000)
     2018/01/08 13:53:51 [WARN] memberlist: Refuting a suspect message  
(from: 20c6ae2b067427648c225c38c28cbfdc-5000)
     2018/01/08 13:53:53 [WARN] memberlist: Refuting a suspect message  
(from: 4c4c3a6fbaa4d7cdb93e4c99ac36193a-5000)
     2018/01/08 13:53:56 [WARN] memberlist: Refuting a suspect message  
(from: 92e491001114e4c1bdee8a380a95d57e-5000)
     2018/01/08 13:54:00 [WARN] memberlist: Refuting a suspect message  
(from: 12547943063eb8b06aa26c70900a5cf7-5000)
     2018/01/08 13:54:04 [INFO] memberlist: Suspect  
08569e435b959c031153a8eb7e2fd92c-5000 has failed, no acks received
     2018/01/08 13:54:05 [INFO] memberlist: Marking  
91a4cc710cd678939bc57030033e63e4-5000 as failed, suspect timeout  
reached (2 peer confirmations)
     2018/01/08 13:54:05 [INFO] serf: EventMemberFailed:  
91a4cc710cd678939bc57030033e63e4-5000 192.168.1.3
     2018/01/08 13:54:06 [INFO] agent: Received event: member-failed
     2018/01/08 13:54:07 [WARN] memberlist: Refuting a suspect message  
(from: c6e794f06aa08ec25b47ce2a276660ed-5000)
     2018/01/08 13:54:09 [WARN] memberlist: Refuting a suspect message  
(from: 9029ce8641b11eb052d5b13997e9d53f-5000)
^C==> Caught signal: interrupt



------------------------------------------------------------------------

Quoting rogerpueyo <notifications@github.com>:
