### ISSUE TITLE
Conflict with mix of nodes with and without IPFS

### ISSUE THREAD

**Issue by felixfreitag** [Clommunity/cDistro#66]
1) "serf members" shows some nodes with only ipfs in tag (.158), without any ipfs initialized in tag (.117), and no ipfs installed (.134): Only search Serf in .134 gets results, others return "no services".

2) tag seems now only to allow exclusively either "ipfssvc" or "services", but not both.
Didn't we say to keep both to be "compatible"?

e21d54f7c23a1b0688892ca58bcd9b5f-5000  10.1.24.158:5000     alive   ipfssvc=QmThBZbEx8LGLE6tm62dfFBiY2xoWa4xdekGzkqrTcx8HE
9cb3537abc519cdf94ec1535765b6839-5000  10.139.40.117:5000   alive   ipfssvc=
629edda5e3ed7c9052a02664ed1f51fb-5000  10.139.40.134:5000   alive   services=QlpoOTFBWSZTWdaUWkcAAEZfgAAQEIVvMCMJXQq/p98qMAC22hqajRoAAAAyAAGqn5UxtCnp6poYgB6QZqepoEqCm1M0TJgBMIMBDN8B2TCMEqEZeMfPqTLCIDMzcYyvVK91QVVVUVlZECJKmxCEiOJAsNDsL7lYqXAUNbYCxgeBZaxLDhcxljGqClYhWqWt2+dKdtkyhkVBJxJ0CD7xERISERm4JwDW4iY+ib0twDg6x+VIgRBHnIIzNr6KCT8emQF4JZ8/u2kfi7kinChIa0otI4A=

**Comment by rogerpueyo** [comment]
Yes, it's a big mess. Code for publication/discovery via IPFS is mixed with IPFS's one (actually it's inside https://github.com/Clommunity/package-serf when it should be in https://github.com/Clommunity/package-ipfs).

I've reverted the changes related to IPFS in Serf (https://github.com/Clommunity/package-serf/commit/d094de4ce4ce7649c3433247af12e9460ff03a26) to fix the search page. The "package-serf" package must be updated, though.
