### ISSUE TITLE
502 Proxy Error

### ISSUE THREAD

**Issue by gabriel-lucas** [Clommunity/cDistro#71]
When using cDistro and trying to install/update the cloudy package, I´m getting the following errors and cDistro panel hangs for some time.

https://server_IP:7443

![cloudy](https://user-images.githubusercontent.com/584454/35903631-523b44e4-0be0-11e8-84cb-8c2f07d24266.png)

Log: /var/log/apache2/error.log

[Wed Feb 07 07:15:44.178082 2018] [proxy:error] [pid 16522] [client 10.38.*.*:55700] AH00898: Error reading from remote server returned by /index.php/cloudyupdate/update/cDistro, referer: https://10.38.*.*:7443/index.php/cloudyupdate
[Wed Feb 07 07:22:28.396433 2018] [proxy_http:error] [pid 16521] (70007)The timeout specified has expired: [client 10.38.*.*:58434] AH01102: error reading status line from remote server localhost:7000, referer: https://10.38.*.*:7443/index.php/cloudyupdate

What could be the issue related with?

**Comment by rogerpueyo** [comment]
By default, the plain HTTP Cloudy web interface is provided by PHP on port 7000. When HTTPS is enabled, a self-signed certificate is generated and Apache2 is configured to act as a reverse proxy and offer on port 7443 what is running -locally- on port 7000.

If, for some reason, the PHP instance serving the web interface crashes, Apache can not reverse-proxy the web interface; this seems to be your case. When updating the cDistro package, the daemon serving the web interface is restarted. It could be that Apache tried to fetch a web page, the cDistro daemon was restarting and it couldn't get the page.

Did the web interface come up again, for instance, when trying to reload the page?

**Comment by gabriel-lucas** [comment]
Thaks for your response @rogerpueyo 
Yes, reloading the web interface brought cDistro interface up again. Since the latest cDistro updates, I´m not having this problem anymore.

**Comment by rogerpueyo** [comment]
Closing, then.
